# Generated by Django 3.2.9 on 2021-11-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_email', models.EmailField(max_length=254)),
                ('agent_contact', models.IntegerField(max_length=255)),
                ('agent_name', models.CharField(max_length=255)),
                ('customer_id', models.IntegerField(max_length=255)),
            ],
        ),
    ]
