# Generated by Django 3.2.9 on 2021-11-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='customer_id',
            field=models.IntegerField(),
        ),
    ]
